### ISSUE TITLE
NoneType object has not attribute channels

### ISSUE THREAD

**Issue by 5HT2** [HTSTEM/DiscordBackup#10]
Hi, it hangs with this error. I probably messed something up but it my bot logs in and then does this.

**Comment by 5HT2** [comment]
```
Backup bot logged in.
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "backup.py", line 38, in on_ready
    await make_logs()
  File "backup.py", line 68, in make_logs
    for channel in guild.channels:
AttributeError: 'NoneType' object has no attribute 'channels'


Backup bot logged in.
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "backup.py", line 38, in on_ready
    await make_logs()
  File "backup.py", line 68, in make_logs
    for channel in guild.channels:
AttributeError: 'NoneType' object has no attribute 'channels'
^C
(cancelled running it here)
Traceback (most recent call last):
  File "backup.py", line 120, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "backup.py", line 26, in main
    client.run(open('token.txt','r').read().split('\n')[0], bot=bot)
  File "/usr/lib/python3.8/site-packages/discord/client.py", line 572, in run
    loop.add_signal_handler(signal.SIGINT, lambda: loop.stop())
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 89, in add_signal_handler
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by hanss314** [comment]
It seems like you provided an invalid guild id. Check that the id is correct and that the bot you are running this on is actually in the guild you are trying to log.

**Comment by 5HT2** [comment]
It is inside my guild. I got the ID by right clicking the guild and hitting copy ID

**Comment by 5HT2** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17222512/72222007-e6311c00-352d-11ea-9f89-1bef2b1555a4.gif)

**Comment by hanss314** [comment]
Did you change `bot=False` to `bot=True`?

**Comment by 5HT2** [comment]
Yep. 
https://pastebin.com/BgTedcJg
this is my `backup.py` in case I missed something
